dataBundle\Entity\periode:
    type: entity
    table: null
    repositoryClass: dataBundle\Repository\periodeRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        dateDebut:
            type: datetime
            column: date_debut
        dateFin:
            type: datetime
            column: date_fin
    oneToMany:
        chaleur:
            targetEntity: dataBundle\Entity\etat
            mappedBy: periode
    lifecycleCallbacks: {  }
