dataBundle\Entity\photoD:
    type: entity
    table: photoChien
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    properties:
        file:
            - File:
                maxSize: 6000000
    fields:
        name:
            type: string
            length: 255
            nullable: true

        path:
            type: string
            length: 255
            nullable: true

    lifecycleCallbacks:

        preUpdate:     [ preUpload ]
        postUpdate:    [ upload ]

        prePersist:   [ preUpload ]
        postPersist:  [ upload ]

        postRemove:   [ removeUpload ]


