<?php

namespace dataBundle\Form;

use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\ChoiceType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class raceType extends AbstractType
{
    /**
     * {@inheritdoc}
     */
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add(
                'libelle' ,
                ChoiceType::class ,
                [
                    'choices'=>
                        [
                            "Affenpinscher "=>"Affenpinscher ",
                            "Airedale Terrier "=>"Airedale Terrier ",
                            "Akita américain "=>"Akita américain ",
                            "Akita Inu "=>"Akita Inu ",
                            "American Staffordshire Terrier "=>"American Staffordshire Terrier ",
                            "Ancien chien d'arrêt danois "=>"Ancien chien d'arrêt danois ",
                            "Anglo-Français de petite vénerie "=>"Anglo-Français de petite vénerie ",
                            "Ariégeois "=>"Ariégeois ",
                            "Azawakh "=>"Azawakh ",
                            "Barbet "=>"Barbet ",
                            "Barbu tchèque "=>"Barbu tchèque ",
                            "Barzoï "=>"Barzoï ",
                            "Basenji "=>"Basenji ",
                            "Basset artésien normand "=>"Basset artésien normand ",
                            "Basset de Westphalie "=>"Basset de Westphalie ",
                            "Basset des Alpes "=>"Basset des Alpes ",
                            "Basset fauve de Bretagne "=>"Basset fauve de Bretagne ",
                            "Basset Hound "=>"Basset Hound ",
                            "Beagle "=>"Beagle ",
                            "Beagle-Harrier "=>"Beagle-Harrier ",
                            "Bearded Collie "=>"Bearded Collie ",
                            "Beauceron "=>"Beauceron ",
                            "Bedlington Terrier "=>"Bedlington Terrier ",
                            "Berger allemand "=>"Berger allemand ",
                            "Berger australien "=>"Berger australien ",
                            "Berger belge "=>"Berger belge ",
                            "Berger blanc suisse "=>"Berger blanc suisse ",
                            "Berger catalan "=>"Berger catalan ",
                            "Berger d'Anatolie "=>"Berger d'Anatolie ",
                            "Berger d'Asie centrale "=>"Berger d'Asie centrale ",
                            "Berger d'Islande "=>"Berger d'Islande ",
                            "Berger de Bergame "=>"Berger de Bergame ",
                            "Berger de Brie "=>"Berger de Brie ",
                            "Berger de l'Atlas "=>"Berger de l'Atlas ",
                            "Berger de Maremme et des Abruzzes "=>"Berger de Maremme et des Abruzzes ",
                            "Berger de Picardie "=>"Berger de Picardie ",
                            "Berger de Russie "=>"Berger de Russie ",
                            "Berger des Pyrénées "=>"Berger des Pyrénées ",
                            "Berger des Shetland "=>"Berger des Shetland ",
                            "Berger du Caucase "=>"Berger du Caucase ",
                            "Berger du massif du Karst "=>"Berger du massif du Karst ",
                            "Berger finnois de Laponie "=>"Berger finnois de Laponie ",
                            "Berger hollandais "=>"Berger hollandais ",
                            "Berger polonais de plaine "=>"Berger polonais de plaine ",
                            "Berger polonais de Podhale "=>"Berger polonais de Podhale ",
                            "Berger portugais "=>"Berger portugais ",
                            "Berger yougoslave "=>"Berger yougoslave ",
                            "Bichon à poil frisé "=>"Bichon à poil frisé ",
                            "Bichon bolonais "=>"Bichon bolonais ",
                            "Bichon havanais "=>"Bichon havanais ",
                            "Bichon maltais "=>"Bichon maltais ",
                            "Billy "=>"Billy ",
                            "Black and tan Coonhound "=>"Black and tan Coonhound ",
                            "Bleu de Gascogne "=>"Bleu de Gascogne ",
                            "Bobtail "=>"Bobtail ",
                            "Boerboel "=>"Boerboel ",
                            "Border Collie "=>"Border Collie ",
                            "Border Terrier "=>"Border Terrier ",
                            "Bouledogue français "=>"Bouledogue français ",
                            "Bouvier bernois "=>"Bouvier bernois ",
                            "Bouvier d'Appenzell "=>"Bouvier d'Appenzell ",
                            "Bouvier d'Australie "=>"Bouvier d'Australie ",
                            "Bouvier de l'Entlebuch "=>"Bouvier de l'Entlebuch ",
                            "Bouvier des Ardennes "=>"Bouvier des Ardennes ",
                            "Bouvier des Flandres "=>"Bouvier des Flandres ",
                            "Boxer "=>"Boxer ",
                            "Brachet allemand "=>"Brachet allemand ",
                            "Brachet autrichien noir et feu "=>"Brachet autrichien noir et feu ",
                            "Brachet de Styrie à poil dur "=>"Brachet de Styrie à poil dur ",
                            "Brachet polonais "=>"Brachet polonais ",
                            "Brachet tyrolien "=>"Brachet tyrolien ",
                            "Braque allemand à poil court "=>"Braque allemand à poil court ",
                            "Braque allemand à poil dur "=>"Braque allemand à poil dur ",
                            "Braque allemand à poil raide "=>"Braque allemand à poil raide ",
                            "Braque d'Auvergne "=>"Braque d'Auvergne ",
                            "Braque de Burgos "=>"Braque de Burgos ",
                            "Braque de l'Ariège "=>"Braque de l'Ariège ",
                            "Braque de Weimar "=>"Braque de Weimar ",
                            "Braque du Bourbonnais "=>"Braque du Bourbonnais ",
                            "Braque français "=>"Braque français ",
                            "Braque hongrois à poil court "=>"Braque hongrois à poil court ",
                            "Braque hongrois à poil dur "=>"Braque hongrois à poil dur ",
                            "Braque italien "=>"Braque italien ",
                            "Braque Saint-Germain "=>"Braque Saint-Germain ",
                            "Braque slovaque à poil dur "=>"Braque slovaque à poil dur ",
                            "Briquet Griffon vendéen "=>"Briquet Griffon vendéen ",
                            "Broholmer "=>"Broholmer ",
                            "Buhund norvégien "=>"Buhund norvégien ",
                            "Bull Terrier "=>"Bull Terrier ",
                            "Bulldog "=>"Bulldog ",
                            "Bullmastiff "=>"Bullmastiff ",
                            "Cairn Terrier "=>"Cairn Terrier ",
                            "Cane Corso "=>"Cane Corso ",
                            "Caniche "=>"Caniche ",
                            "Cão de Castro Laboreiro "=>"Cão de Castro Laboreiro ",
                            "Cão fila de São Miguel "=>"Cão fila de São Miguel ",
                            "Carlin "=>"Carlin ",
                            "Cavalier King Charles Spaniel "=>"Cavalier King Charles Spaniel ",
                            "Chesapeake Bay Retriever "=>"Chesapeake Bay Retriever ",
                            "Chien chinois à crête "=>"Chien chinois à crête ",
                            "Chien courant d'Istrie à poil dur "=>"Chien courant d'Istrie à poil dur ",
                            "Chien courant d'Istrie à poil ras "=>"Chien courant d'Istrie à poil ras ",
                            "Chien courant de Bosnie à poil dur "=>"Chien courant de Bosnie à poil dur ",
                            "Chien courant de Halden "=>"Chien courant de Halden ",
                            "Chien courant de Hygen "=>"Chien courant de Hygen ",
                            "Chien courant de Posavatz "=>"Chien courant de Posavatz ",
                            "Chien courant de Transylvanie "=>"Chien courant de Transylvanie ",
                            "Chien courant espagnol "=>"Chien courant espagnol ",
                            "Chien courant finnois "=>"Chien courant finnois ",
                            "Chien courant hellénique "=>"Chien courant hellénique ",
                            "Chien courant italien "=>"Chien courant italien ",
                            "Chien courant serbe "=>"Chien courant serbe ",
                            "Chien courant slovaque "=>"Chien courant slovaque ",
                            "Chien courant suisse "=>"Chien courant suisse ",
                            "Chien courant yougoslave de montagne "=>"Chien courant yougoslave de montagne ",
                            "Chien courant yougoslave tricolore "=>"Chien courant yougoslave tricolore ",
                            "Chien d'arrêt allemand à poil long "=>"Chien d'arrêt allemand à poil long ",
                            "Chien d'arrêt portugais "=>"Chien d'arrêt portugais ",
                            "Chien d'Artois "=>"Chien d'Artois ",
                            "Chien d'eau américain "=>"Chien d'eau américain ",
                            "Chien d'eau espagnol "=>"Chien d'eau espagnol ",
                            "Chien d'eau frison "=>"Chien d'eau frison ",
                            "Chien d'eau irlandais "=>"Chien d'eau irlandais ",
                            "Chien d'eau portugais "=>"Chien d'eau portugais ",
                            "Chien d'eau romagnol "=>"Chien d'eau romagnol ",
                            "Chien d'élan norvégien "=>"Chien d'élan norvégien ",
                            "Chien d'élan suédois "=>"Chien d'élan suédois ",
                            "Chien d'ours de Carélie "=>"Chien d'ours de Carélie ",
                            "Chien d'Oysel "=>"Chien d'Oysel ",
                            "Chien de berger de Croatie "=>"Chien de berger de Croatie ",
                            "Chien de berger de Majorque "=>"Chien de berger de Majorque ",
                            "Chien de Canaan "=>"Chien de Canaan ",
                            "Chien de montagne des Pyrénées "=>"Chien de montagne des Pyrénées ",
                            "Chien de montagne portugais "=>"Chien de montagne portugais ",
                            "Chien de Saint-Hubert "=>"Chien de Saint-Hubert ",
                            "Chien de Taïwan "=>"Chien de Taïwan ",
                            "Chien du Groenland "=>"Chien du Groenland ",
                            "Chien du pharaon "=>"Chien du pharaon ",
                            "Chien finnois de Laponie "=>"Chien finnois de Laponie ",
                            "Chien norvégien de Macareux "=>"Chien norvégien de Macareux ",
                            "Chien nu du Pérou "=>"Chien nu du Pérou ",
                            "Chien nu mexicain "=>"Chien nu mexicain ",
                            "Chien rouge de Bavière "=>"Chien rouge de Bavière ",
                            "Chien rouge de Hanovre "=>"Chien rouge de Hanovre ",
                            "Chien suédois de Laponie "=>"Chien suédois de Laponie ",
                            "Chien thaïlandais "=>"Chien thaïlandais ",
                            "Chien-loup de Saarloos "=>"Chien-loup de Saarloos ",
                            "Chien-loup tchèque "=>"Chien-loup tchèque ",
                            "Chihuahua "=>"Chihuahua ",
                            "Chow-Chow "=>"Chow-Chow ",
                            "Cirneco de l'Etna "=>"Cirneco de l'Etna ",
                            "Clumber Spaniel "=>"Clumber Spaniel ",
                            "Cocker américain "=>"Cocker américain ",
                            "Cocker anglais "=>"Cocker anglais ",
                            "Colley à poil court "=>"Colley à poil court ",
                            "Colley à poil long "=>"Colley à poil long ",
                            "Coton de Tuléar "=>"Coton de Tuléar ",
                            "Curly-Coated Retriever "=>"Curly-Coated Retriever ",
                            "Dalmatien "=>"Dalmatien ",
                            "Dandie Dinmont Terrier "=>"Dandie Dinmont Terrier ",
                            "Dobermann "=>"Dobermann ",
                            "Dogo canario "=>"Dogo canario ",
                            "Dogue allemand "=>"Dogue allemand ",
                            "Dogue argentin "=>"Dogue argentin ",
                            "Dogue de Bordeaux "=>"Dogue de Bordeaux ",
                            "Dogue de Majorque "=>"Dogue de Majorque ",
                            "Dogue du Tibet "=>"Dogue du Tibet ",
                            "Drever "=>"Drever ",
                            "Dunker "=>"Dunker ",
                            "Épagneul à perdrix de Drente "=>"Épagneul à perdrix de Drente ",
                            "Épagneul bleu de Picardie "=>"Épagneul bleu de Picardie ",
                            "Épagneul breton "=>"Épagneul breton ",
                            "Épagneul de Pont-Audemer "=>"Épagneul de Pont-Audemer ",
                            "Épagneul français "=>"Épagneul français ",
                            "Épagneul japonais "=>"Épagneul japonais ",
                            "Épagneul nain continental "=>"Épagneul nain continental ",
                            "Épagneul picard "=>"Épagneul picard ",
                            "Épagneul tibétain "=>"Épagneul tibétain ",
                            "Eurasier "=>"Eurasier ",
                            "Field Spaniel "=>"Field Spaniel ",
                            "Fila brasileiro "=>"Fila brasileiro ",
                            "Flat-Coated Retriever "=>"Flat-Coated Retriever ",
                            "Fox-Terrier "=>"Fox-Terrier ",
                            "Foxhound américain "=>"Foxhound américain ",
                            "Foxhound anglais "=>"Foxhound anglais ",
                            "Français blanc et noir "=>"Français blanc et noir ",
                            "Français blanc et orange "=>"Français blanc et orange ",
                            "Français tricolore "=>"Français tricolore ",
                            "Golden Retriever "=>"Golden Retriever ",
                            "Grand Anglo-Français blanc et noir "=>"Grand Anglo-Français blanc et noir ",
                            "Grand Anglo-Français blanc et orange "=>"Grand Anglo-Français blanc et orange ",
                            "Grand Anglo-Français tricolore "=>"Grand Anglo-Français tricolore ",
                            "Grand Basset Griffon vendéen "=>"Grand Basset Griffon vendéen ",
                            "Grand bouvier suisse "=>"Grand bouvier suisse ",
                            "Grand Gascon saintongeois "=>"Grand Gascon saintongeois ",
                            "Grand Griffon vendéen "=>"Grand Griffon vendéen ",
                            "Grand Münsterländer "=>"Grand Münsterländer ",
                            "Greyhound "=>"Greyhound ",
                            "Griffon à poil dur Korthals "=>"Griffon à poil dur Korthals ",
                            "Griffon belge "=>"Griffon belge ",
                            "Griffon bruxellois "=>"Griffon bruxellois ",
                            "Griffon fauve de Bretagne "=>"Griffon fauve de Bretagne ",
                            "Griffon nivernais "=>"Griffon nivernais ",
                            "Hamilton stövare "=>"Hamilton stövare ",
                            "Harrier "=>"Harrier ",
                            "Hokkaido Ken "=>"Hokkaido Ken ",
                            "Hovawart "=>"Hovawart ",
                            "Husky sibérien "=>"Husky sibérien ",
                            "Irish Glen of Imaal Terrier "=>"Irish Glen of Imaal Terrier ",
                            "Irish Terrier "=>"Irish Terrier ",
                            "Irish Terrier à poil doux "=>"Irish Terrier à poil doux ",
                            "Jack Russell Terrier "=>"Jack Russell Terrier ",
                            "Jagdterrier "=>"Jagdterrier ",
                            "Kai "=>"Kai ",
                            "Kelpie "=>"Kelpie ",
                            "Kerry Blue Terrier "=>"Kerry Blue Terrier ",
                            "King Charles Spaniel "=>"King Charles Spaniel ",
                            "Kishu "=>"Kishu ",
                            "Komondor "=>"Komondor ",
                            "Korea Jindo dog "=>"Korea Jindo dog ",
                            "Kromfohrländer "=>"Kromfohrländer ",
                            "Kuvasz "=>"Kuvasz ",
                            "Labrador Retriever "=>"Labrador Retriever ",
                            "Laika de Sibérie occidentale "=>"Laika de Sibérie occidentale ",
                            "Laïka de Sibérie orientale "=>"Laïka de Sibérie orientale ",
                            "Laïka russe européen "=>"Laïka russe européen ",
                            "Lakeland Terrier "=>"Lakeland Terrier ",
                            "Landseer "=>"Landseer ",
                            "Leonberger "=>"Leonberger ",
                            "Lévrier afghan "=>"Lévrier afghan ",
                            "Lévrier écossais "=>"Lévrier écossais ",
                            "Lévrier espagnol "=>"Lévrier espagnol ",
                            "Lévrier hongrois "=>"Lévrier hongrois ",
                            "Lévrier irlandais "=>"Lévrier irlandais ",
                            "Lévrier polonais "=>"Lévrier polonais ",
                            "Lhassa Apso "=>"Lhassa Apso ",
                            "Malamute de l'Alaska "=>"Malamute de l'Alaska ",
                            "Manchester Terrier "=>"Manchester Terrier ",
                            "Mastiff "=>"Mastiff ",
                            "Mâtin des Pyrénées "=>"Mâtin des Pyrénées ",
                            "Mâtin espagnol "=>"Mâtin espagnol ",
                            "Mâtin napolitain "=>"Mâtin napolitain ",
                            "Mudi "=>"Mudi ",
                            "Norfolk Terrier et Norwich Terrier "=>"Norfolk Terrier et Norwich Terrier ",
                            "Otterhound "=>"Otterhound ",
                            "Parson Russell Terrier "=>"Parson Russell Terrier ",
                            "Pékinois "=>"Pékinois ",
                            "Petit Basset Griffon vendéen "=>"Petit Basset Griffon vendéen ",
                            "Petit brabançon "=>"Petit brabançon ",
                            "Petit chien courant suisse "=>"Petit chien courant suisse ",
                            "Petit chien hollandais de chasse au gibier d'eau "=>"Petit chien hollandais de chasse au gibier d'eau ",
                            "Petit chien lion "=>"Petit chien lion ",
                            "Petit Gascon saintongeois "=>"Petit Gascon saintongeois ",
                            "Petit Lévrier italien "=>"Petit Lévrier italien ",
                            "Petit Münsterländer "=>"Petit Münsterländer ",
                            "Pinscher "=>"Pinscher ",
                            "Pinscher autrichien à poil court "=>"Pinscher autrichien à poil court ",
                            "Podenco canario "=>"Podenco canario ",
                            "Podenco ibicenco "=>"Podenco ibicenco ",
                            "Podenco portugais "=>"Podenco portugais ",
                            "Pointer anglais "=>"Pointer anglais ",
                            "Poitevin "=>"Poitevin ",
                            "Porcelaine "=>"Porcelaine ",
                            "Pudelpointer "=>"Pudelpointer ",
                            "Puli "=>"Puli ",
                            "Pumi "=>"Pumi ",
                            "Rafeiro do Alentejo "=>"Rafeiro do Alentejo ",
                            "Retriever de la Nouvelle-Écosse "=>"Retriever de la Nouvelle-Écosse ",
                            "Rhodesian Ridgeback "=>"Rhodesian Ridgeback ",
                            "Rottweiler "=>"Rottweiler ",
                            "Russkiy Toy "=>"Russkiy Toy ",
                            "Saint-Bernard "=>"Saint-Bernard ",
                            "Saluki "=>"Saluki ",
                            "Samoyède "=>"Samoyède ",
                            "Schapendoes néerlandais "=>"Schapendoes néerlandais ",
                            "Schiller stövare "=>"Schiller stövare ",
                            "Schipperke "=>"Schipperke ",
                            "Schnauzer "=>"Schnauzer ",
                            "Scottish Terrier "=>"Scottish Terrier ",
                            "Sealyham Terrier "=>"Sealyham Terrier ",
                            "Setter anglais "=>"Setter anglais ",
                            "Setter Gordon "=>"Setter Gordon ",
                            "Setter irlandais "=>"Setter irlandais ",
                            "Setter irlandais rouge et blanc "=>"Setter irlandais rouge et blanc ",
                            "Shar Pei "=>"Shar Pei ",
                            "Shiba Inu "=>"Shiba Inu ",
                            "Shih Tzu "=>"Shih Tzu ",
                            "Shikoku "=>"Shikoku ",
                            "Silky Terrier "=>"Silky Terrier ",
                            "Skye Terrier "=>"Skye Terrier ",
                            "Sloughi "=>"Sloughi ",
                            "Slovensky cuvac "=>"Slovensky cuvac ",
                            "Småland stövare "=>"Småland stövare ",
                            "Smous des Pays-Bas "=>"Smous des Pays-Bas ",
                            "Spinone "=>"Spinone ",
                            "Spitz allemand "=>"Spitz allemand ",
                            "Spitz de Norbotten "=>"Spitz de Norbotten ",
                            "Spitz des Wisigoths "=>"Spitz des Wisigoths ",
                            "Spitz finlandais "=>"Spitz finlandais ",
                            "Spitz japonais "=>"Spitz japonais ",
                            "Springer anglais "=>"Springer anglais ",
                            "Stabyhoun "=>"Stabyhoun ",
                            "Staffordshire Bull Terrier "=>"Staffordshire Bull Terrier ",
                            "Sussex Spaniel "=>"Sussex Spaniel ",
                            "Teckel "=>"Teckel ",
                            "Terre-Neuve "=>"Terre-Neuve ",
                            "Terrier australien "=>"Terrier australien ",
                            "Terrier brésilien "=>"Terrier brésilien ",
                            "Terrier de Boston "=>"Terrier de Boston ",
                            "Terrier japonais "=>"Terrier japonais ",
                            "Terrier noir russe "=>"Terrier noir russe ",
                            "Terrier tchèque "=>"Terrier tchèque ",
                            "Terrier tibétain "=>"Terrier tibétain ",
                            "Tosa "=>"Tosa ",
                            "Toy Terrier anglais noir et feu "=>"Toy Terrier anglais noir et feu ",
                            "Volpino "=>"Volpino ",
                            "Welsh Corgi "=>"Welsh Corgi ",
                            "Welsh Springer Spaniel "=>"Welsh Springer Spaniel ",
                            "Welsh Terrier "=>"Welsh Terrier ",
                            "West Highland White Terrier "=>"West Highland White Terrier ",
                            "Whippet "=>"Whippet ",
                            "Yorkshire Terrier"=>"Yorkshire Terrier",
                        ]
                ]
            )
            ->add('type')
            ->add('info')        ;
    }
    
    /**
     * {@inheritdoc}
     */
    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults(array(
            'data_class' => 'dataBundle\Entity\race'
        ));
    }

    /**
     * {@inheritdoc}
     */
    public function getBlockPrefix()
    {
        return 'databundle_race';
    }


}
