<?php

namespace dataBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * dresseursRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class dresseursRepository extends EntityRepository
{
}
