<?php

namespace dataBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * periodeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class periodeRepository extends EntityRepository
{
}
